- name: Pull and deploy
  hosts: localhost
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: zaqbez39me/moscow-time-app:latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: moscow-time
        image: zaqbez39me/moscow-time-app:latest
        state: started
        ports:
          - "1235:80"
  roles:
    - docker
  become: True