- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true
  tags: docker

- name: Install Docker Compose via pip
  pip:
    name: docker-compose
    state: latest
  tags: docker
  notify: start_docker